export interface UploadProxyResult {
  status: number;
  contentType: string;
  body: Buffer;
}

type FetchLike = (input: string | URL, init?: RequestInit) => Promise<Response>;

// Matches the names generated by ProfilePhotoStorage: `<uuid>.<jpg|png|webp>`.
const PROFILE_PHOTO_FILENAME = /^[a-f0-9-]+\.(jpg|png|webp)$/;

export class UploadsProxyService {
  constructor(
    private readonly employeeServiceUrl: string,
    private readonly fetcher: FetchLike = fetch,
  ) {}

  async getProfilePhoto(filename: string): Promise<UploadProxyResult> {
    if (!PROFILE_PHOTO_FILENAME.test(filename)) return notFound();

    const response = await this.fetcher(`${this.employeeServiceUrl}/uploads/profile/${filename}`);
    if (!response.ok) return notFound();

    return {
      status: response.status,
      contentType: response.headers.get('content-type') ?? 'application/octet-stream',
      body: Buffer.from(await response.arrayBuffer()),
    };
  }
}

function notFound(): UploadProxyResult {
  return { status: 404, contentType: 'application/json', body: Buffer.from(JSON.stringify({ code: 'NOT_FOUND' })) };
}
